name: Deploy Web

on:
  workflow_dispatch:
    inputs:
      api-url:
        description: "api url"
        default: "https://motor-rental-shop.pockethost.io/"
        required: false
        type: string
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  build:
    name: Build & Deploy
    env:
      API_URL: ${{ inputs.api-url || 'https://motor-rental-shop.pockethost.io/' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4
      - name: Create dotenv file
        if: env.API_URL != ''
        run: echo "API_URL=${{ env.API_URL }}" > dotenv
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web --release --web-renderer html --base-href /motor_rental_shop/
      - run: |
          cd build/web
          git init
          git config --global user.email toandv@zyyx.jp
          git config --global user.name zyyx-toandv
          git status
          git remote add origin https://${{ secrets.SECRET_TOKEN }}@github.com/dgtoan/motor_rental_shop.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
          cd ../..
